# Generated by Django 5.0.6 on 2024-06-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desafioadl", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtarea",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
